# Publish docker images to dockerhub

name: Docker Publish

on:
  release:
    types: [published]

jobs:
  publish_image:
    name: Push InvenTree web server image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: cd
        run: |
          cd docker
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: inventree/inventree
          tag_with_ref: true
          dockerfile: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
